imports_granularity = "Crate"
use_small_heuristics = "Max"
comment_width = 100
wrap_comments = true
use_field_init_shorthand = true
format_code_in_doc_comments = true
max_width = 120
group_imports = "StdExternalCrate"
newline_style = "Unix"
normalize_comments = true
